vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        flat_images:
            uri_prefix: /images/flat
            upload_destination: '%kernel.project_dir%/public/images/flat'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer